Step 1 : Load Weather and Solar data

In [33]:
import pandas as pd

# Load weather data
weather_bakersfield = pd.read_csv("bakersfield_weather.csv")
weather_la = pd.read_csv("la_weather.csv")
weather_phoenix = pd.read_csv("phoenix_weather.csv")
weather_sf = pd.read_csv("sf_weather.csv")
weather_chicago = pd.read_csv("chicago_weather.csv")
weather_ny = pd.read_csv("ny_weather.csv")
weather_miami = pd.read_csv("miami_weather.csv")
weather_denver = pd.read_csv("denver_weather.csv")

# Load solar data
solar_bakersfield = pd.read_csv("solar_bakersfield.csv")
solar_la = pd.read_csv("solar_la.csv")
solar_phoenix = pd.read_csv("solar_phoenix.csv")
solar_miami = pd.read_csv("solar_miami.csv")
solar_ny = pd.read_csv("solar_ny.csv")
solar_sf = pd.read_csv("solar_sf.csv")
solar_denver = pd.read_csv("solar_denver.csv")
solar_chicago = pd.read_csv("solar_chicago.csv")


# Display a few rows of each dataset
print("Weather - Bakersfield:")
print(weather_bakersfield.head())
print("\nSolar - Bakersfield:")
print(solar_bakersfield.head())

#Different format weather city files
print("Weather - San Francisco:")
print(weather_sf.head())
print("\nSolar - San Francisco:")
print(solar_sf.head())

Weather - Bakersfield:
       STATION                NAME      DATE  AWND  DAPR  MDPR  PGTM  PRCP  \
0  USC00048122  SHAFTER 6 E, CA US  01/01/15   NaN   NaN   NaN   NaN   0.0
1  USC00048122  SHAFTER 6 E, CA US  02/01/15   NaN   NaN   NaN   NaN   0.0
2  USC00048122  SHAFTER 6 E, CA US  03/01/15   NaN   NaN   NaN   NaN   0.0
3  USC00048122  SHAFTER 6 E, CA US  04/01/15   NaN   NaN   NaN   NaN   0.0
4  USC00048122  SHAFTER 6 E, CA US  05/01/15   NaN   NaN   NaN   NaN   0.0

   SNOW  SNWD  ...  WESF  WSF2  WSF5  WT01  WT02  WT03  WT05  WT07  WT08  WT11
0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 27 columns]

Solar - Bakersfield:
   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DNI  CLRSKY_SFC_SW_DWN  \
0  2015   1   1               3.41               7.91               3.42
1  2015   1   2               3.39               7.66               3.39
2  2015   1   3               3.34               7.44               3.34
3  2015   1   4               3.00               4.60               3.32
4  2015   1   5               3.20               6.51               3.23

   ALLSKY_SFC_SW_DIFF  ALLSKY_KT  ALLSKY_SFC_UV_INDEX  ALLSKY_SFC_UVB  \
0                0.52       0.74                 0.41            0.08
1                0.55       0.73                 0.49            0.10
2                0.54       0.72                 0.46            0.09
3                1.29       0.64                 0.45            0.09
4                0.65       0.68                 0.43            0.09

   ALLSKY_SFC_UVA  ALLSKY_SFC_PAR_TOT
0            6.82               58.83
1            6.84               58.79
2            6.84               58.79
3            6.42               53.24
4            6.70               57.50
Weather - San Francisco:
         date  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0  2015-01-01   9.7   4.4  12.8   0.0   NaN  38.0  13.7   NaN  1020.1   NaN
1  2015-01-02   7.7   3.3  11.1   0.0   NaN   NaN   2.5   NaN  1021.7   NaN
2  2015-01-03   7.7   3.3  12.2   0.0   NaN   NaN   2.5   NaN  1024.3   NaN
3  2015-01-04   8.6   5.0  12.8   0.0   NaN   NaN   3.2   NaN  1028.5   NaN
4  2015-01-05   9.8   6.1  15.0   0.0   NaN   NaN   4.0   NaN  1026.7   NaN

Solar - San Francisco:
   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DNI  CLRSKY_SFC_SW_DWN  \
0  2015   1   1               3.07               7.30               3.07
1  2015   1   2               2.91               6.26               2.95
2  2015   1   3               2.89               6.20               2.93
3  2015   1   4               2.43               2.70               2.95
4  2015   1   5               2.54               2.70               3.00

   ALLSKY_SFC_SW_DIFF  ALLSKY_KT  ALLSKY_SFC_UV_INDEX  ALLSKY_SFC_UVB  \
0                0.52       0.72                 0.38            0.08
1                0.66       0.68                 0.37            0.08
2                0.66       0.67                 0.37            0.07
3                1.41       0.56                 0.34            0.07
4                1.62       0.59                 0.36            0.07

   ALLSKY_SFC_UVA  ALLSKY_SFC_PAR_TOT
0            6.09               53.73
1            5.92               51.84
2            5.95               51.95
3            5.42               44.21
4            5.63               46.54

Step 2: Clean and Standardize Weather and Solar Data

In [34]:
# Check a few rows to identify date format inconsistencies
print(weather_bakersfield['DATE'].head(10))  # Check first 20 rows for Bakersfield

#Another format
print(weather_sf['date'].head(10))

0    01/01/15
1    02/01/15
2    03/01/15
3    04/01/15
4    05/01/15
5    06/01/15
6    07/01/15
7    08/01/15
8    09/01/15
9    10/01/15
Name: DATE, dtype: object
0    2015-01-01
1    2015-01-02
2    2015-01-03
3    2015-01-04
4    2015-01-05
5    2015-01-06
6    2015-01-07
7    2015-01-08
8    2015-01-09
9    2015-01-10
Name: date, dtype: object

In [35]:
#Converting the new cities file to existing cities file format

# San Francisco
weather_sf["STATION"] = "KSFKO"
weather_sf["NAME"] = "San Francisco International Airport"
weather_sf = weather_sf.rename(
    columns={
        "date": "DATE",
        "tavg": "TAVG",
        "tmin": "TMIN",
        "tmax": "TMAX",
        "prcp": "PRCP",
        "snow": "SNOW",
        "wdir": "WDF2",
        "wspd": "AWND",
        "wpgt": "WSF2",
    }
)
sf_missing_columns = [
    "DAPR", "MDPR", "PGTM", "SNWD", "TOBS", "WDF5", "WESD", "WESF",
    "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]
for col in sf_missing_columns:
    weather_sf[col] = None
weather_sf = weather_sf[[
    "STATION", "NAME", "DATE", "AWND", "DAPR", "MDPR", "PGTM", "PRCP", "SNOW",
    "SNWD", "TAVG", "TMAX", "TMIN", "TOBS", "WDF2", "WDF5", "WESD", "WESF",
    "WSF2", "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]]

# New York
weather_ny["STATION"] = "KWO-35"
weather_ny["NAME"] = "New York Wall Street"
weather_ny = weather_ny.rename(
    columns={
        "date": "DATE",
        "tavg": "TAVG",
        "tmin": "TMIN",
        "tmax": "TMAX",
        "prcp": "PRCP",
        "snow": "SNOW",
        "wdir": "WDF2",
        "wspd": "AWND",
        "wpgt": "WSF2",
    }
)
for col in sf_missing_columns:
    weather_ny[col] = None
weather_ny = weather_ny[[
    "STATION", "NAME", "DATE", "AWND", "DAPR", "MDPR", "PGTM", "PRCP", "SNOW",
    "SNWD", "TAVG", "TMAX", "TMIN", "TOBS", "WDF2", "WDF5", "WESD", "WESF",
    "WSF2", "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]]

# Chicago
weather_chicago["STATION"] = "KMDW"
weather_chicago["NAME"] = "Chicago Midway International Airport"
weather_chicago = weather_chicago.rename(
    columns={
        "date": "DATE",
        "tavg": "TAVG",
        "tmin": "TMIN",
        "tmax": "TMAX",
        "prcp": "PRCP",
        "snow": "SNOW",
        "wdir": "WDF2",
        "wspd": "AWND",
        "wpgt": "WSF2",
    }
)
for col in sf_missing_columns:
    weather_chicago[col] = None
weather_chicago = weather_chicago[[
    "STATION", "NAME", "DATE", "AWND", "DAPR", "MDPR", "PGTM", "PRCP", "SNOW",
    "SNWD", "TAVG", "TMAX", "TMIN", "TOBS", "WDF2", "WDF5", "WESD", "WESF",
    "WSF2", "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]]

# Miami
weather_miami["STATION"] = "KMIA"
weather_miami["NAME"] = "Miami International Airport"
weather_miami = weather_miami.rename(
    columns={
        "date": "DATE",
        "tavg": "TAVG",
        "tmin": "TMIN",
        "tmax": "TMAX",
        "prcp": "PRCP",
        "snow": "SNOW",
        "wdir": "WDF2",
        "wspd": "AWND",
        "wpgt": "WSF2",
    }
)
for col in sf_missing_columns:
    weather_miami[col] = None
weather_miami = weather_miami[[
    "STATION", "NAME", "DATE", "AWND", "DAPR", "MDPR", "PGTM", "PRCP", "SNOW",
    "SNWD", "TAVG", "TMAX", "TMIN", "TOBS", "WDF2", "WDF5", "WESD", "WESF",
    "WSF2", "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]]

# Denver
weather_denver["STATION"] = "KDEN"
weather_denver["NAME"] = "Denver International Airport (DEN)"
weather_denver = weather_denver.rename(
    columns={
        "date": "DATE",
        "tavg": "TAVG",
        "tmin": "TMIN",
        "tmax": "TMAX",
        "prcp": "PRCP",
        "snow": "SNOW",
        "wdir": "WDF2",
        "wspd": "AWND",
        "wpgt": "WSF2",
    }
)
for col in sf_missing_columns:
    weather_denver[col] = None
weather_denver = weather_denver[[
    "STATION", "NAME", "DATE", "AWND", "DAPR", "MDPR", "PGTM", "PRCP", "SNOW",
    "SNWD", "TAVG", "TMAX", "TMIN", "TOBS", "WDF2", "WDF5", "WESD", "WESF",
    "WSF2", "WSF5", "WT01", "WT02", "WT03", "WT05", "WT07", "WT08", "WT11"
]]

In [36]:
#Checking the file format

print("Weather - San Francisco:")
print(weather_sf.head())

Weather - San Francisco:
  STATION                                 NAME        DATE  AWND  DAPR  MDPR  \
0   KSFKO  San Francisco International Airport  2015-01-01  13.7  None  None
1   KSFKO  San Francisco International Airport  2015-01-02   2.5  None  None
2   KSFKO  San Francisco International Airport  2015-01-03   2.5  None  None
3   KSFKO  San Francisco International Airport  2015-01-04   3.2  None  None
4   KSFKO  San Francisco International Airport  2015-01-05   4.0  None  None

   PGTM  PRCP  SNOW  SNWD  ...  WESF  WSF2  WSF5  WT01  WT02  WT03  WT05  \
0  None   0.0   NaN  None  ...  None   NaN  None  None  None  None  None
1  None   0.0   NaN  None  ...  None   NaN  None  None  None  None  None
2  None   0.0   NaN  None  ...  None   NaN  None  None  None  None  None
3  None   0.0   NaN  None  ...  None   NaN  None  None  None  None  None
4  None   0.0   NaN  None  ...  None   NaN  None  None  None  None  None

   WT07  WT08  WT11
0  None  None  None
1  None  None  None
2  None  None  None
3  None  None  None
4  None  None  None

[5 rows x 27 columns]

A. Converting Dates to a Uniform Format

In [38]:
# Standardizing weather data dates with mixed or ambiguous formats
weather_bakersfield['DATE'] = pd.to_datetime(weather_bakersfield['DATE'], dayfirst=True, errors='coerce')
weather_la['DATE'] = pd.to_datetime(weather_la['DATE'], dayfirst=True, errors='coerce')
weather_phoenix['DATE'] = pd.to_datetime(weather_phoenix['DATE'], dayfirst=True, errors='coerce')


print(weather_bakersfield['DATE'].head())
print("Missing Dates")
print(weather_bakersfield['DATE'].isna().sum())  # Count missing dates

print("New cities format check of date field")
print(weather_sf['DATE'].head())
print(weather_sf['DATE'].isna().sum())  # Count missing dates

0   2015-01-01
1   2015-01-02
2   2015-01-03
3   2015-01-04
4   2015-01-05
Name: DATE, dtype: datetime64[ns]
Missing Dates
0
New cities format check of date field
0    2015-01-01
1    2015-01-02
2    2015-01-03
3    2015-01-04
4    2015-01-05
Name: DATE, dtype: object
0

In [39]:
# Check for invalid YEAR, MO, DY combinations
print(solar_bakersfield[['YEAR', 'MO', 'DY']].head())
print(solar_bakersfield[['YEAR', 'MO', 'DY']].isna().sum())  # Ensure no missing values

   YEAR  MO  DY
0  2015   1   1
1  2015   1   2
2  2015   1   3
3  2015   1   4
4  2015   1   5
YEAR    0
MO      0
DY      0
dtype: int64

In [40]:
# Creating DATE column in solar data
solar_bakersfield['DATE'] = pd.to_datetime(
    solar_bakersfield[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_la['DATE'] = pd.to_datetime(
    solar_la[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_phoenix['DATE'] = pd.to_datetime(
    solar_phoenix[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_sf['DATE'] = pd.to_datetime(
    solar_sf[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_ny['DATE'] = pd.to_datetime(
    solar_ny[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_chicago['DATE'] = pd.to_datetime(
    solar_chicago[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_denver['DATE'] = pd.to_datetime(
    solar_denver[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)
solar_miami['DATE'] = pd.to_datetime(
    solar_miami[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1)
)

In [41]:
# Drop YEAR, MO, DY columns after creating DATE
solar_bakersfield.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_la.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_phoenix.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_sf.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_ny.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_chicago.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_miami.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)
solar_denver.drop(['YEAR', 'MO', 'DY'], axis=1, inplace=True)

B. Filtering Relevant Columns

In [42]:
# Select relevant weather columns
weather_columns = ['STATION', 'NAME', 'DATE', 'TAVG', 'TMAX', 'TMIN', 'PRCP' , 'SNOW']
weather_bakersfield = weather_bakersfield[weather_columns]
weather_la = weather_la[weather_columns]
weather_phoenix = weather_phoenix[weather_columns]
weather_sf = weather_sf[weather_columns]
weather_ny = weather_ny[weather_columns]
weather_chicago = weather_chicago[weather_columns]
weather_miami = weather_miami[weather_columns]
weather_denver = weather_denver[weather_columns]

# Select relevant solar columns
solar_columns = ['DATE', 'ALLSKY_SFC_SW_DWN', 'CLRSKY_SFC_SW_DWN', 'ALLSKY_SFC_SW_DIFF']
solar_bakersfield = solar_bakersfield[solar_columns]
solar_la = solar_la[solar_columns]
solar_phoenix = solar_phoenix[solar_columns]
solar_sf = solar_sf[solar_columns]
solar_ny = solar_ny[solar_columns]
solar_chicago = solar_chicago[solar_columns]
solar_miami = solar_miami[solar_columns]
solar_denver = solar_denver[solar_columns]

C. Checking and Handling Missing Values

In [43]:
# Check missing values

# Bakersfield
print("Weather - Bakersfield Missing Values:")
print(weather_bakersfield.isnull().sum())
print("\nSolar - Bakersfield Missing Values:")
print(solar_bakersfield.isnull().sum())


#LA
print("\nWeather - LA Missing Values:")
print(weather_la.isnull().sum())
print("\nSolar - LA Missing Values:")
print(solar_la.isnull().sum())

#Phoenix
print("\nWeather - Phoenix Missing Values:")
print(weather_phoenix.isnull().sum())
print("\nSolar - Phoenix Missing Values:")
print(solar_phoenix.isnull().sum())

Weather - Bakersfield Missing Values:
STATION        0
NAME           0
DATE           0
TAVG       11259
TMAX        3547
TMIN        3589
PRCP          49
SNOW        8986
dtype: int64

Solar - Bakersfield Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - LA Missing Values:
STATION         0
NAME            0
DATE            0
TAVG       174807
TMAX       118848
TMIN       119031
PRCP        39566
SNOW       136752
dtype: int64

Solar - LA Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - Phoenix Missing Values:
STATION         0
NAME            0
DATE            0
TAVG       370109
TMAX       333640
TMIN       333506
PRCP         2732
SNOW        94870
dtype: int64

Solar - Phoenix Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

In [44]:
#SF
print("\nWeather - SF Missing Values:")
print(weather_sf.isnull().sum())
print("\nSolar - SF Missing Values:")
print(solar_sf.isnull().sum())


#NY
print("\nWeather - NY Missing Values:")
print(weather_ny.isnull().sum())
print("\nSolar - NY Missing Values:")
print(solar_ny.isnull().sum())

#Chicago
print("\nWeather - Chicago Missing Values:")
print(weather_chicago.isnull().sum())
print("\nSolar - Chicago Missing Values:")
print(solar_chicago.isnull().sum())


#Miami
print("\nWeather - Miami Missing Values:")
print(weather_miami.isnull().sum())
print("\nSolar - Miami Missing Values:")
print(solar_miami.isnull().sum())


#Denver
print("\nWeather - Denver Missing Values:")
print(weather_denver.isnull().sum())
print("\nSolar - Denver Missing Values:")
print(solar_denver.isnull().sum())

Weather - SF Missing Values:
STATION       0
NAME          0
DATE          0
TAVG          0
TMAX          0
TMIN          0
PRCP          0
SNOW       2812
dtype: int64

Solar - SF Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - NY Missing Values:
STATION       0
NAME          0
DATE          0
TAVG        703
TMAX        703
TMIN        703
PRCP       2199
SNOW       3608
dtype: int64

Solar - NY Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - Chicago Missing Values:
STATION    0
NAME       0
DATE       0
TAVG       9
TMAX       0
TMIN       0
PRCP       0
SNOW       7
dtype: int64

Solar - Chicago Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - Miami Missing Values:
STATION       0
NAME          0
DATE          0
TAVG          0
TMAX          0
TMIN          0
PRCP          0
SNOW       1297
dtype: int64

Solar - Miami Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

Weather - Denver Missing Values:
STATION    0
NAME       0
DATE       0
TAVG       1
TMAX       0
TMIN       0
PRCP       0
SNOW       8
dtype: int64

Solar - Denver Missing Values:
DATE                  0
ALLSKY_SFC_SW_DWN     0
CLRSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DIFF    0
dtype: int64

In [45]:
# Droping rows with missing DATE and TAVG

#Bakersfield
weather_bakersfield.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_bakersfield.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)

#LA
weather_la.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_la.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)

#Phoenix
weather_phoenix.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_phoenix.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)


#SF
weather_sf.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_sf.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)


#NY
weather_ny.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_ny.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)


#Chicago
weather_chicago.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_chicago.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)


#Miami
weather_miami.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_miami.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)


#Denver
weather_denver.dropna(subset=['DATE', 'TAVG'], inplace=True)
solar_denver.dropna(subset=['DATE', 'ALLSKY_SFC_SW_DWN'], inplace=True)

D. Adding City Column for Context

In [46]:
# Add CITY column to weather data
weather_bakersfield['CITY'] = 'Bakersfield'
weather_la['CITY'] = 'Los Angeles'
weather_phoenix['CITY'] = 'Phoenix'
weather_sf['CITY'] = "San Francisco"
weather_ny['CITY'] = "New York"
weather_chicago['CITY'] =  "Chicago"
weather_miami['CITY'] = "Miami"
weather_denver['CITY'] = "Denver"

# Add CITY column to solar data
solar_bakersfield['CITY'] = 'Bakersfield'
solar_la['CITY'] = 'Los Angeles'
solar_phoenix['CITY'] = 'Phoenix'
solar_sf['CITY'] = "San Francisco"
solar_ny['CITY'] = "New York"
solar_chicago['CITY'] =  "Chicago"
solar_miami['CITY'] = "Miami"
solar_denver['CITY'] = "Denver"

In [47]:
# Checking after cleaning

print(weather_bakersfield.head())
print(solar_bakersfield.head())

          STATION                        NAME       DATE  TAVG  TMAX  TMIN  \
6087  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-01  40.0  54.0  28.0
6088  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-02  42.0  54.0  30.0
6089  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-03  42.0  55.0  31.0
6090  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-04  43.0  58.0  31.0
6091  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-05  45.0  59.0  33.0

      PRCP  SNOW         CITY
6087   0.0   0.0  Bakersfield
6088   0.0   0.0  Bakersfield
6089   0.0   0.0  Bakersfield
6090   0.0   0.0  Bakersfield
6091   0.0   0.0  Bakersfield
        DATE  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DIFF  \
0 2015-01-01               3.41               3.42                0.52
1 2015-01-02               3.39               3.39                0.55
2 2015-01-03               3.34               3.34                0.54
3 2015-01-04               3.00               3.32                1.29
4 2015-01-05               3.20               3.23                0.65

          CITY
0  Bakersfield
1  Bakersfield
2  Bakersfield
3  Bakersfield
4  Bakersfield

E. Cross Checking If any Duplicates based on Date are present

In [49]:
# Find duplicates by DATE
duplicates = weather_bakersfield[weather_bakersfield.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#la
# Find rows where DATE is duplicated (ignoring other columns)
duplicates = weather_la[weather_la.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows


#Phoenix
duplicates = weather_phoenix[weather_phoenix.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#Sf
duplicates = weather_sf[weather_sf.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#Ny
duplicates = weather_ny[weather_ny.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#Chicago
duplicates = weather_chicago[weather_chicago.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#Miami
duplicates = weather_miami[weather_miami.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

#Denver
duplicates = weather_denver[weather_denver.duplicated(subset=['DATE'], keep=False)]
print(duplicates.head())  # Inspect duplicate rows

Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []
       STATION                                 NAME       DATE  TAVG  TMAX  \
0  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-01  47.0  58.0
1  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-02  48.0  59.0
2  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-03  50.0  63.0
3  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-04  52.0  70.0
4  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-05  59.0  82.0

   TMIN  PRCP  SNOW         CITY
0  36.0   0.0   NaN  Los Angeles
1  38.0   0.0   NaN  Los Angeles
2  39.0   0.0   NaN  Los Angeles
3  41.0   0.0   NaN  Los Angeles
4  45.0   0.0   NaN  Los Angeles
            STATION                    NAME       DATE  TAVG  TMAX  TMIN  \
9287    USW00023183  PHOENIX AIRPORT, AZ US 2017-01-01  56.0  57.0  52.0
86560   USW00023183  PHOENIX AIRPORT, AZ US 2017-01-01  56.0  57.0  52.0
87290   USW00023183  PHOENIX AIRPORT, AZ US 2019-01-01  43.0  51.0  38.0
165509  USW00023183  PHOENIX AIRPORT, AZ US 2019-01-01  43.0  51.0  38.0
166240  USW00023183  PHOENIX AIRPORT, AZ US 2021-01-01  51.0  65.0  39.0

        PRCP  SNOW     CITY
9287     0.2   NaN  Phoenix
86560    0.2   NaN  Phoenix
87290    0.0   NaN  Phoenix
165509   0.0   NaN  Phoenix
166240   0.0   NaN  Phoenix
Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []
Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []
Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []
Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []
Empty DataFrame
Columns: [STATION, NAME, DATE, TAVG, TMAX, TMIN, PRCP, SNOW, CITY]
Index: []

For Pheonix and LA: a) Removing exact duplicates

In [50]:
# Remove exact duplicates based on 'DATE'
weather_phoenix_cleaned = weather_phoenix.drop_duplicates(subset=['DATE'], keep='first')
weather_la_cleaned = weather_la.drop_duplicates(subset=['DATE'], keep='first')

b) If there are multiple stations aggregating duplicate entries by date

In [62]:
# Phoenix Aggregation
weather_phoenix_aggregated = weather_phoenix_cleaned.groupby('DATE').agg({
    'STATION': 'first',  # Taking the first station
    'NAME': 'first',     # Taking the first name
    'TAVG': 'mean',
    'TMAX': 'mean',
    'TMIN': 'mean',
    'PRCP': 'mean',
    'SNOW': 'mean',      # Aggregating SNOW with mean (or use 'first' or another method if needed)
    'CITY': 'first'      # Taking the first city
}).reset_index()

# Ensure the columns are in the correct order
weather_phoenix_aggregated = weather_phoenix_aggregated[['STATION', 'NAME', 'DATE', 'TAVG', 'TMAX', 'TMIN', 'PRCP', 'SNOW', 'CITY']]

# Sort data by DATE to preserve chronological order
weather_phoenix_aggregated = weather_phoenix_aggregated.sort_values(by='DATE').reset_index(drop=True)

# LA Aggregation
weather_la_aggregated = weather_la_cleaned.groupby('DATE').agg({
    'STATION': 'first',  # Taking the first station
    'NAME': 'first',     # Taking the first name
    'TAVG': 'mean',
    'TMAX': 'mean',
    'TMIN': 'mean',
    'PRCP': 'mean',
    'SNOW': 'mean',      # Aggregating SNOW with mean (or use 'first' or another method if needed)
    'CITY': 'first'      # Taking the first city
}).reset_index()

# Ensure the columns are in the correct order
weather_la_aggregated = weather_la_aggregated[['STATION', 'NAME', 'DATE', 'TAVG', 'TMAX', 'TMIN', 'PRCP', 'SNOW', 'CITY']]

# Sort data by DATE to preserve chronological order
weather_la_aggregated = weather_la_aggregated.sort_values(by='DATE').reset_index(drop=True)

# Inspect the cleaned data
print(weather_phoenix_aggregated.head())
print(weather_la_aggregated.head())

       STATION                    NAME       DATE  TAVG   TMAX  TMIN  PRCP  \
0  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-01  40.0   46.0  35.0   0.0
1  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-02  56.0   69.0  50.0   0.0
2  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-03  66.0   77.0  61.0   0.0
3  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-04  82.0   91.0  67.0   0.0
4  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-05  86.0  101.0  70.0   0.0

   SNOW     CITY
0   NaN  Phoenix
1   NaN  Phoenix
2   NaN  Phoenix
3   NaN  Phoenix
4   NaN  Phoenix
       STATION                                 NAME       DATE  TAVG  TMAX  \
0  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-01  47.0  58.0
1  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-02  48.0  59.0
2  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-03  50.0  63.0
3  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-04  52.0  70.0
4  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-05  59.0  82.0

   TMIN  PRCP  SNOW         CITY
0  36.0   0.0   NaN  Los Angeles
1  38.0   0.0   NaN  Los Angeles
2  39.0   0.0   NaN  Los Angeles
3  41.0   0.0   NaN  Los Angeles
4  45.0   0.0   NaN  Los Angeles

Step 3 : Merging Weather and Solar Data

A. Ensuring Date Formats Match

In [63]:
# Convert the 'DATE' columns to datetime format for both weather and solar data
weather_bakersfield['DATE'] = pd.to_datetime(weather_bakersfield['DATE'])
weather_la_aggregated['DATE'] = pd.to_datetime(weather_la_aggregated['DATE'])
weather_phoenix_aggregated['DATE'] = pd.to_datetime(weather_phoenix_aggregated['DATE'])
weather_sf['DATE'] = pd.to_datetime(weather_sf['DATE'])
weather_ny['DATE'] = pd.to_datetime(weather_ny['DATE'])
weather_chicago['DATE'] = pd.to_datetime(weather_chicago['DATE'])
weather_miami['DATE'] = pd.to_datetime(weather_miami['DATE'])
weather_denver['DATE'] = pd.to_datetime(weather_denver['DATE'])




solar_bakersfield['DATE'] = pd.to_datetime(solar_bakersfield['DATE'])
solar_la['DATE'] = pd.to_datetime(solar_la['DATE'])
solar_phoenix['DATE'] = pd.to_datetime(solar_phoenix['DATE'])
solar_sf['DATE'] = pd.to_datetime(solar_sf['DATE'])
solar_ny['DATE'] = pd.to_datetime(solar_ny['DATE'])
solar_chicago['DATE'] = pd.to_datetime(solar_chicago['DATE'])
solar_miami['DATE'] = pd.to_datetime(solar_miami['DATE'])
solar_denver['DATE'] = pd.to_datetime(solar_denver['DATE'])

B. Merging the Data for Each City

In [64]:
# Merging weather and solar data for each city

# Bakersfield
merged_bakersfield = pd.merge(weather_bakersfield, solar_bakersfield, on='DATE', how='inner')
# Los Angeles
merged_la = pd.merge(weather_la_aggregated, solar_la, on='DATE', how='inner')
# Phoenix
merged_phoenix = pd.merge(weather_phoenix_aggregated, solar_phoenix, on='DATE', how='inner')
#Sf
merged_sf = pd.merge(weather_sf, solar_sf, on='DATE', how='inner')
#Ny
merged_ny = pd.merge(weather_ny, solar_ny, on='DATE', how='inner')
#Chicago
merged_chicago = pd.merge(weather_chicago, solar_chicago, on='DATE', how='inner')
#Miami
merged_miami = pd.merge(weather_miami, solar_miami, on='DATE', how='inner')
#Denver
merged_denver = pd.merge(weather_denver, solar_denver, on='DATE', how='inner')


# Checking the merged data for few cities
print("\nMerged Bakersfield:")
print(merged_bakersfield.head())

print("\nMerged Los Angeles:")
print(merged_la.head())

print("\nMerged Phoenix:")
print(merged_phoenix.head())

print("\nMerged San Francisco:")
print(merged_sf.head())

Merged Bakersfield:
       STATION                        NAME       DATE  TAVG  TMAX  TMIN  PRCP  \
0  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-01  40.0  54.0  28.0   0.0
1  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-02  42.0  54.0  30.0   0.0
2  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-03  42.0  55.0  31.0   0.0
3  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-04  43.0  58.0  31.0   0.0
4  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-05  45.0  59.0  33.0   0.0

   SNOW       CITY_x  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  \
0   0.0  Bakersfield               3.41               3.42
1   0.0  Bakersfield               3.39               3.39
2   0.0  Bakersfield               3.34               3.34
3   0.0  Bakersfield               3.00               3.32
4   0.0  Bakersfield               3.20               3.23

   ALLSKY_SFC_SW_DIFF       CITY_y
0                0.52  Bakersfield
1                0.55  Bakersfield
2                0.54  Bakersfield
3                1.29  Bakersfield
4                0.65  Bakersfield

Merged Los Angeles:
       STATION                                 NAME       DATE  TAVG  TMAX  \
0  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-01  47.0  58.0
1  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-02  48.0  59.0
2  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-03  50.0  63.0
3  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-04  52.0  70.0
4  USW00023129  LONG BEACH DAUGHERTY AIRPORT, CA US 2015-01-05  59.0  82.0

   TMIN  PRCP  SNOW       CITY_x  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  \
0  36.0   0.0   NaN  Los Angeles               3.59               3.62
1  38.0   0.0   NaN  Los Angeles               3.56               3.56
2  39.0   0.0   NaN  Los Angeles               3.50               3.50
3  41.0   0.0   NaN  Los Angeles               3.25               3.50
4  45.0   0.0   NaN  Los Angeles               3.43               3.49

   ALLSKY_SFC_SW_DIFF       CITY_y
0                0.56  Los Angeles
1                0.52  Los Angeles
2                0.55  Los Angeles
3                1.09  Los Angeles
4                0.65  Los Angeles

Merged Phoenix:
       STATION                    NAME       DATE  TAVG   TMAX  TMIN  PRCP  \
0  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-01  40.0   46.0  35.0   0.0
1  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-02  56.0   69.0  50.0   0.0
2  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-03  66.0   77.0  61.0   0.0
3  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-04  82.0   91.0  67.0   0.0
4  USW00023183  PHOENIX AIRPORT, AZ US 2015-01-05  86.0  101.0  70.0   0.0

   SNOW   CITY_x  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DIFF  \
0   NaN  Phoenix               2.37               3.61                1.20
1   NaN  Phoenix               3.71               3.65                0.56
2   NaN  Phoenix               3.71               3.65                0.48
3   NaN  Phoenix               3.72               3.67                0.47
4   NaN  Phoenix               3.77               3.74                0.54

    CITY_y
0  Phoenix
1  Phoenix
2  Phoenix
3  Phoenix
4  Phoenix

Merged San Francisco:
  STATION                                 NAME       DATE  TAVG  TMAX  TMIN  \
0   KSFKO  San Francisco International Airport 2015-01-01   9.7  12.8   4.4
1   KSFKO  San Francisco International Airport 2015-01-02   7.7  11.1   3.3
2   KSFKO  San Francisco International Airport 2015-01-03   7.7  12.2   3.3
3   KSFKO  San Francisco International Airport 2015-01-04   8.6  12.8   5.0
4   KSFKO  San Francisco International Airport 2015-01-05   9.8  15.0   6.1

   PRCP  SNOW         CITY_x  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  \
0   0.0   NaN  San Francisco               3.07               3.07
1   0.0   NaN  San Francisco               2.91               2.95
2   0.0   NaN  San Francisco               2.89               2.93
3   0.0   NaN  San Francisco               2.43               2.95
4   0.0   NaN  San Francisco               2.54               3.00

   ALLSKY_SFC_SW_DIFF         CITY_y
0                0.52  San Francisco
1                0.66  San Francisco
2                0.66  San Francisco
3                1.41  San Francisco
4                1.62  San Francisco

C. Combine All City Data

In [65]:
# Combine all merged city data into one DataFrame
merged_all_cities = pd.concat([merged_bakersfield, merged_la, merged_phoenix, merged_sf, merged_ny , merged_chicago , merged_miami , merged_denver], ignore_index=True)

# Inspect the final merged dataset
print("Merged Data for All Cities:")
print(merged_all_cities.head())

Merged Data for All Cities:
       STATION                        NAME       DATE  TAVG  TMAX  TMIN  PRCP  \
0  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-01  40.0  54.0  28.0   0.0
1  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-02  42.0  54.0  30.0   0.0
2  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-03  42.0  55.0  31.0   0.0
3  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-04  43.0  58.0  31.0   0.0
4  USW00023155  BAKERSFIELD AIRPORT, CA US 2015-01-05  45.0  59.0  33.0   0.0

   SNOW       CITY_x  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_SW_DWN  \
0   0.0  Bakersfield               3.41               3.42
1   0.0  Bakersfield               3.39               3.39
2   0.0  Bakersfield               3.34               3.34
3   0.0  Bakersfield               3.00               3.32
4   0.0  Bakersfield               3.20               3.23

   ALLSKY_SFC_SW_DIFF       CITY_y
0                0.52  Bakersfield
1                0.55  Bakersfield
2                0.54  Bakersfield
3                1.29  Bakersfield
4                0.65  Bakersfield

D. Exporting the Final Dataset

In [66]:
# Export the final merged data to CSV
merged_all_cities.to_csv('merged_cleaned_data.csv', index=False)